### ISSUE TITLE
Issue with multiple SPFx solutions or SPFx + other solution open in Visual Studio Code

### ISSUE THREAD

**Issue by StfBauer** [estruyf/vscode-spfx-task-runner#1]
imaging the scenario for some reason I have SPFx project + another or two SPFx projects open.

The problem with the task runner is that I cannot cherry pick which solution to build, package, ...
If there is another project open I get the message that this is not an SPFx project.

Screenshot of a scenario where angular-spfx is the Visual Studio Project:
<img width="682" alt="screenshot 2018-10-08 at 09 12 56" src="https://user-images.githubusercontent.com/5503835/46595813-8a7e1480-cada-11e8-800f-0195fd0e8a1f.png">

Error message in console:
<img width="834" alt="screenshot 2018-10-08 at 09 14 40" src="https://user-images.githubusercontent.com/5503835/46595853-9ec21180-cada-11e8-8a89-779694a65c85.png">

**Comment by estruyf** [comment]
@StfBauer that would be a great enhancement and I have included support for this in release `1.2.0`. Now in order to make it work, you will have to do some work on your project side as well. By default VSCode scans for tasks only on the root level, not in sub-folders. This is why the extension didn't work.

Now in order to make it work, you will have to create a workspace. This lets VSCode know that the folders are actual project folders, and it will check for tasks not on the root level, but in the project folders. In order to do this, you can click on `file` -> `Save workspace as ...`. This will ask you for a name. 

![screenshot 2019-02-07 10 42 03](https://user-images.githubusercontent.com/2900833/52402696-3f463380-2ac5-11e9-9282-aac66db7bd09.png)

Once provided, it will create a `workpace-name.code-workspace` file. In here all you have to do is specify the configuration of the project folders.

![screenshot 2019-02-07 10 44 17](https://user-images.githubusercontent.com/2900833/52402729-538a3080-2ac5-11e9-9e0e-ad025691707e.png)

Save the file and now you can open the workspace via the file. You'll notice that the folders icons will be a bit different.

![screenshot 2019-02-07 10 44 55](https://user-images.githubusercontent.com/2900833/52402816-80d6de80-2ac5-11e9-9d8f-2df7e84cadda.png)

This might be a good enhancement as well for the `@pnp/generator-spfx` to automatically create the `*.code-workspace` file for `Angular` type projects.
